### ISSUE TITLE
Once godaddy nameservers are applyed, consecutive runs will fail with 404

### ISSUE THREAD

**Issue by Noctris** [n3integration/terraform-godaddy#11]
Hi,

First of all thanks for this provider ! We use it in our setup to update the godaddy nameservers from our azure dns zone.

We notice that once the records are updated, all consecutive runs will fail with a [404:UNKNOWN . DOMAIN]

I am not sure if this is a godaddy api issue or code here .

Steps to reproduce:

1: Create godaddy_domain_record and plan & apply

`
resource "godaddy_domain_record" "gd_domain_com" {
  domain = "domain.com"

  nameservers = ["${substr(azurerm_dns_zone.domain_com.name_servers[0],0,length(azurerm_dns_zone.domain_com.name_servers[0])-1)}"]
`

2: Redo plan & apply and you will get:

`
Error refreshing state: 1 error(s) occurred:

* godaddy_domain_record.gd_domain_com: 1 error(s) occurred:

* godaddy_domain_record.gd_domain_com: godaddy_domain_record.gd_domain_com: couldn't find domain record (domain.com): [404:UNKNOWN_DOMAIN] The given domain is not registered, or does not have a zone file
`

even though all works fine and godaddy config is correct. I'm thinking they way the api checks for domain existence does not work well with custom nameservers.

PS: The azurerm provider returns ns servers with a trailing dot like this:

> ns1-01.azure-dns.net.

which cannot be verified by the godaddy api and throws strange errors. Might be usefull to check for this too because you cannot use the standard provider map output ${azurerm_dns_zone.domain_com.name_servers} because of this and have to substr the trailing dot.

**Comment by n3integration** [comment]
Hey @Noctris - Thanks for the bug report! I'll take a stab at reproducing the behavior that you're describing.

**Comment by n3integration** [comment]
I've experienced this behavior a few times as well. It *may* be a consistency issue, but I don't know for sure. If I wait for a couple of minutes and refresh the service again a few more times, the update will go through as expected. I'll have to do some more digging.

**Comment by ryanohoro** [comment]
I'm having the same issue now. 

The problem is that if you do not manage DNS records in GoDaddy (only set external nameservers) and Terraform goes to populate the resource data, the provider requests /v1/domains/example.com/records in resource_dns_record.go which returns a 404 because there are no DNS (zone) records for domains with external nameservers.

The error "couldn't find domain record" is never reached because the 404 throws an error beforehand. This error should likely be ignored, and the data populated by populateResourceDataFromResponse would need to be handled differently. Perhaps moved to populateDomainInfo? The nameservers for the domain are returned from /v1/domains/example.com.

I'm not certain there's a reliable way to determine if external nameservers are being used, but if you get a 200 from /v1/domain/example.com and 404 from /v1/domain/example.com/records, that's a hint.

**Comment by n3integration** [comment]
Hey @ryanohoro - All good information. I'll take another look at this issue and see if I can reproduce it reliably with the details provided. Thanks!

**Comment by edahlseng** [comment]
Just ran into this same error. Are there any updates on this issue?

**Comment by ryanohoro** [comment]
Because I'm not versed in Go, I haven't been able to figure out how to write a patch for this unfortunately.

**Comment by martindube** [comment]
I'm having the same issue. 

With `nameservers` var commented, I get: `[422:MISSING_NAME_SERVER] At least two NS records must be specified in the request body`

With `nameservers` var set, I get: `[422:FAILED_NAME_SERVER_VALIDATION] Failed to update nameservers (records [INVALID_FIELD]: Nameservers [ns65.domaincontrol.com] , records [INVALID_FIELD]: Nameservers [ns66.domaincontrol.com] )` where ns65 and ns66 are the currently configured NS.

**Comment by ryanohoro** [comment]
This appears to be new behavior from GoDaddy. I tested it extensively this week, and GoDaddy is now refusing to allow API users to re-delegate GoDaddy as the DNS provider. This must now be done through the console UI, as setting the default nameservers.

It appears the only way to address this is to more or less fake the update, as it's not possible to set those nameservers anymore.

**Comment by vsayer** [comment]
Can reproduce what @martindube is seeing.

**Comment by n3integration** [comment]
@ryanohoro , @vsayer, @martindube - I've published a new release of the plugin to address the recent GoDaddy API changes.

**Comment by n3integration** [comment]
closing issue...

**Comment by thanks4wifi** [comment]
This is still an issue.

```
Error: couldn't find domain record (example.com): [404:UNKNOWN_DOMAIN] The given domain is not registered, or does not have a zone file
```

I've done a deeper dive into the issue and have posted notes here
https://gist.github.com/thanks4wifi/162220394cd5c02ed0779f4f5f64fb82

**Comment by cevich** [comment]
I just hit this issue, and struggled with it quite a bit before finding this ***closed*** issue.  I can confirm that the workaround permanently resolved this issue.  In my case I'm delegating control of the domain to another provider.  So my only godaddy resource simply sets the name-servers.

To restate it, the workaround was:

1. In DNS Management, click "Change" and set the option to "I'll use GoDaddy nameservers (recommended)".
2. Follow the instructions (sometimes e-mail confirmation is needed).
3. Give some time (30 minutes or so) for any SOA changes to propagate.
4. Re-apply your terraform configuration.

I'm sure plenty of users are hitting this, *not* finding this closed issue, and giving up.  It would be really, ***REALLY***, nice to have this note/workaround included in the main README and/or terraform provider documentation :grin:
